apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: traefik-dashboard
    path: ./ingressroute-patch.yaml