apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
helmCharts:
- name: prometheus
  includeCRDs: true
  releaseName: prometheus
  version: 15.5.3
  repo: https://prometheus-community.github.io/helm-charts
resources:
- prometheus_ns.yaml
