apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
helmCharts:
- name: traefik
  includeCRDs: true
  releaseName: traefik
  version: 23.0.1
  repo: https://traefik.github.io/charts
resources: []
